spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/team-maker
    username: sa
    password: 1234
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 30
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    properties:
      hibernate:
        show_sql: true
        format_sql: true